### ISSUE TITLE
Include file name collisions due to flattened namespace.

### ISSUE THREAD

**Issue by rakshasa** [trema/trema#134]
The project makes excessive use of include directories making headers from different parts of the project accessible through the root include. This is bound to cause issues when the project grows larger.

E.g. ./src/lib/foo.h should only be accessible through "lib/foo.h", ./ruby/trema/foo.h from "ruby/trema/foo.h", etc.

**Comment by yasuhito** [comment]
The Trema C support will be dropped in the next release https://github.com/trema/trema/tree/feature/trema_ruby. So I would like to close this issue for the present though we might fix this later.
