### ISSUE TITLE
Conflict between ./cruise.rb and active ovs-switchd not detected.

### ISSUE THREAD

**Issue by rakshasa** [trema/trema#138]
The unittests will randomly fail if there is an active ovs-switchd trying to connect to 127.0.0.1:6633, which would not be that uncommon during development.

Possible solutions would be to use a different port for these tests or produce an error when starting the ./cruise.rb script.

**Comment by yasuhito** [comment]
cruise.rb has been deprecated in a recent release so I would close this issue.
