### ISSUE TITLE
Do not embed absolute paths in libtrema.a

### ISSUE THREAD

**Issue by sugyo** [trema/trema#17]
When debugging with other persons core file, we cannot view source code because absolute paths are embedded in libtrema.a

<pre>
#0  0xb7f0e424 in ?? () from /lib/i686/cmov/libc.so.6
(gdb) bt
#0  0xb7f0e424 in ?? () from /lib/i686/cmov/libc.so.6
#1  0xb7e79fdd in ?? () from /lib/i686/cmov/libc.so.6
#2  0x0805269d in start_messenger ()
    at /home/.../trema/src/lib/messenger.c:1704
#3  0x0805404f in start_trema ()
    at /home/.../trema/src/lib/trema.c:570
#4  0x0804c297 in main (argc=5, argv=0xbfd2b1c4)
    at src/switch_manager/switch.c:449
</pre>

**Comment by yasuhito** [comment]
The Trema C support will be dropped in the next release of Trema, so I would close this for now.
