### ISSUE TITLE
log dir cannot be specified directly

### ISSUE THREAD

**Issue by amotoki** [trema/trema#243]
ログ, pid 格納, sock 格納用のディレクトリが TREMA_TMP 配下に作成され、配置をカスタマイズできない。

主なディストリビューションでは、以下のように配置するのが一般的であり、
この構成を取れるとよい。

 * $TREMA_TMP/log -> /var/log/trema
 * $TREMA_TMP/pid -> /var/run/trema or /var/run/trema/pid
 * $TREMA_TMP/sock -> /var/run/trema or /var/run/trema/sock

**Comment by yasuhito** [comment]
trema run にログディレクトリ、pidディレクトリ、socketディレクトリを指定できるオプションが追加してあります。オプションの詳細は、こちらです https://relishapp.com/trema/trema/docs/trema-run
