### ISSUE TITLE
TDD flow in Trema book does not work with the latest Trema

### ISSUE THREAD

**Issue by stakizawa** [trema/trema#263]
Test-driven development flow explained in the Trema book (クラウド時代のネットワーク技術 OpenFlow実践入門) does not work with the latest trema (commit: a956f1e679f19f8ae6cadfb48b8f06e902a21918).

To run a rspec test program, I have to do the following additional tasks.

1. create $TREMA_HOME/tmp/log and $TREMA_HOME/tmp/pid directories. If $TREMA_HOME/tmp/log does not exist, switch_manager does not start. If $TREMA_HOME/tmp/pid does not exist, phost fails to write pid file.

    $ mkdir $TREMA_HOME/tmp/log
    $ mkdir $TREMA_HOME/tmp/pid

2. comment out the following lines in $TREMA_HOME/spec/spec_helper.rb.  These lines disable rspec's 'should' method.
```ruby
RSpec.configure do | config |
  config.expect_with :rspec do | c |
    # Ensure that 'expect' is used and disable 'should' for consistency
    c.syntax = :expect
  end
end
```

**Comment by yasuhito** [comment]
TremaのテストはCucumberに移行したので、本に書いてあるRSpecの書き方は動かないと思います。Cucumberでの書き方についてはいま本を書き中なのでしばしお待ちください。。
