### ISSUE TITLE
Enable controller common options without "" when using trema run

### ISSUE THREAD

**Issue by y-higuchi** [trema/trema#271]
Current trema run requires trema controller common options like `--name` , `--logging_level`, etc. to be enclosed in quotes with the controller name in order for them to take effect.  

    $ trema run "./controller --name=NewName" -d

It will be easier to use, if trema run command passed those options to the controller, when common options were given to trema run and enable trema run invocation like:

    $ trema run ./controller --name=NewName -d 
 

Note that simply appending common options found to the end of controllers option arguments may cause problem, 
when there are controller specifc options.   

    $ trema run "./controller -a -b -c -- other arguments" --name=NewName -d

In the above case, `--name=NewName` probably should be inserted after `-c`

**Comment by yasuhito** [comment]
In the next coming release, controller specific options can be passed after `--`. Read https://github.com/trema/routing_switch/ example for details.
