### ISSUE TITLE
Exception in Trema

### ISSUE THREAD

**Issue by nitin456** [trema/trema#319]
Hi All,

When I run my trema app, sometimes it gives exception like following.
nitin@nitin-Vostro-1015:~/trema$ sudo  trema run ./filedemo
Hello Trema
/var/lib/gems/1.8/gems/trema-0.3.20/ruby/trema/util.rb:32:in `sh': Command './filedemo --name filedemo ' failed! (RuntimeError)
	from /var/lib/gems/1.8/gems/trema-0.3.20/ruby/trema/daemon.rb:77:in `run!'
	from /var/lib/gems/1.8/gems/trema-0.3.20/ruby/trema/dsl/runner.rb:157:in `maybe_run_apps'
	from /var/lib/gems/1.8/gems/trema-0.3.20/ruby/trema/dsl/runner.rb:156:in `fork'
	from /var/lib/gems/1.8/gems/trema-0.3.20/ruby/trema/dsl/runner.rb:156:in `maybe_run_apps'
	from /var/lib/gems/1.8/gems/trema-0.3.20/ruby/trema/dsl/runner.rb:34:in `run'
	from /var/lib/gems/1.8/gems/trema-0.3.20/ruby/trema/command/run.rb:44:in `trema_run'
	from /var/lib/gems/1.8/gems/trema-0.3.20/././bin/trema:64:in `initialize'
	from /var/lib/gems/1.8/gems/gli-2.6.2/lib/gli/command_support.rb:121:in `call'
	from /var/lib/gems/1.8/gems/gli-2.6.2/lib/gli/command_support.rb:121:in `execute'
	from /var/lib/gems/1.8/gems/gli-2.6.2/lib/gli/app_support.rb:276:in `call_command'
	from /var/lib/gems/1.8/gems/gli-2.6.2/lib/gli/app_support.rb:289:in `call'
	from /var/lib/gems/1.8/gems/gli-2.6.2/lib/gli/app_support.rb:289:in `call_command'
	from /var/lib/gems/1.8/gems/gli-2.6.2/lib/gli/app_support.rb:79:in `run'
	from /var/lib/gems/1.8/gems/trema-0.3.20/././bin/trema:288:in `start'
	from /var/lib/gems/1.8/gems/trema-0.3.20/././bin/trema:300

 What is wrong with that ?

 Thanks
 Nitin

**Comment by yasuhito** [comment]
@nitin456 How can I reproduce the error?
