### ISSUE TITLE
Configuration file in Trema

### ISSUE THREAD

**Issue by nitin456** [trema/trema#325]
Hi All,

Do we have any documentation to define the flow of applications in trema configuration file.
For examples: 
event :port_status => "topology", :packet_in => "filter", :state_notify => "topology"
filter :lldp => "topology_discovery", :packet_in => "routing_switch"

I do not understand how does it work?

Thanks 
Nitin

**Comment by yasuhito** [comment]
The feature is deprecated in the latest release. If you still need such functionality please read https://github.com/trema/routing_switch/blob/develop/lib/routing_switch.rb this example implements dispatching and filtering of OF messages.
