### ISSUE TITLE
unit tests don't build because of missing static libraries

### ISSUE THREAD

**Issue by infrastation** [trema/trema#326]
Some Linux distributions that are otherwise OK to build and run Trema (at least Fedora) don't provide static versions of the libraries required by the unit tests (in particular, libsqlite3x and libpcap). Unit tests thus cannot be built:
```
 /usr/bin/ld: cannot find -lsqlite3
 /usr/bin/ld: cannot find -lpthread
 /usr/bin/ld: cannot find -lrt
 /usr/bin/ld: cannot find -ldl
 /usr/bin/ld: cannot find -lc
```

**Comment by yasuhito** [comment]
The C part of Trema is entirely replaced with Ruby code in the latest release so this issue is  already fixed.
