### ISSUE TITLE
Default port number

### ISSUE THREAD

**Issue by sugyo** [trema/trema#333]
Q. Why did change the port number to 6653?
A. 6653 has been defined in openflow 1.0.2
https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.0.2.pdf

Q. How do I change the OpenFlow port number to 6633?
A. For example:

    $ echo 'port 6633' > /tmp/openflow_port.conf
    $ ./trema run ./src/examples/learning_switch/learning-switch.rb -c /tmp/openflow_port.conf -d
    $ lsof -P -i4 -a -p `cat tmp/pid/switch_manager.pid`
    COMMAND     PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
    switch_ma 31591 sugyo    6u  IPv4 204733      0t0  TCP *:6633 (LISTEN)
    $

**Comment by yasuhito** [comment]
Since IANA assigned port 6653 for OpenFlow channel, the default port of Trema is now 6653. It can be overwritten by using -p (--port) option. Also updated the FAQ page.
