### ISSUE TITLE
port number  in the trema.conf is ignored

### ISSUE THREAD

**Issue by sugyo** [trema/trema#335]
trema.confに書いたportは無視されます。port場所でも動作がかわる(これは昔かららしい)

    $ cat > /tmp/port_6633.conf
    # before vswitch
    port 6633 # ignored by switch_manager

    vswitch {
      datapath_id "0xabc"
    }

    $ ./trema --verbose run .../learning-switch.rb --conf=/tmp/port_6633.conf
    .../switch_manager .............. --port=6653
    sudo .../ovs-openflowd ... tcp:127.0.0.1:6633
    ...
    $ ./trema --verbose run ..../learning-switch.rb --port=6633 --conf=/tmp/port_6633.conf
    .../switch_manager .............. --port=6633
    sudo .../ovs-openflowd ... tcp:127.0.0.1:6633
    ...
    $  cat > /tmp/undefined_port.conf
    # undefined port

    vswitch {
      datapath_id "0xabc"
    }

    $ ./trema --verbose run ..../learning-switch.rb --conf=/tmp/undefined_port.conf
    .../switch_manager .............. --port=6653
    sudo .../ovs-openflowd ... tcp:127.0.0.1:6653
    ...
    $ ./trema --verbose run ..../learning-switch.rb --port=6633 --conf=/tmp/undefined_port.conf
    .../switch_manager .............. --port=6633
    sudo .../ovs-openflowd ... tcp:127.0.0.1:6653
    ...
    $ cat > /tmp/vswitch_port_6633.conf

    vswitch {
      datapath_id "0xabc"
    }
 
    # after vswitch
    port 6633 # ignored by switch_manager and ovs-openflowd

    $ ./trema --verbose run ..../learning-switch.rb --conf=/tmp/vswitch_port_6633.conf
    .../switch_manager .............. --port=6653
    sudo .../ovs-openflowd ... tcp:127.0.0.1:6653
    ...
    $ ./trema --verbose run ..../learning-switch.rb --port=6633 --conf=/tmp/vswitch_port_6633.conf
    .../switch_manager .............. --port=6633
    sudo .../ovs-openflowd ... tcp:127.0.0.1:6653
    ...
    $

**Comment by yasuhito** [comment]
trema run に -p と --port を付けました && trema.conf にはポート番号は書けないようにしました。
