### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [trema/trema#381]
Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Signal management") ⇒ [main](https://github.com/trema/trema/blob/3e77cede34fad44c1b4170f1f5674994521c7cb2/src/switch_manager/switch_manager.c#L578 "main function")
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [create_hash_with_size](https://github.com/trema/trema/blob/3e77cede34fad44c1b4170f1f5674994521c7cb2/src/lib/hash_table.c#L82 "Creates a new hash table")

**Comment by yasuhito** [comment]
The C version of Trema will be dropped in the next coming release so this won't be fixed.
