### ISSUE TITLE
flow_modのデフォルトのmatch

### ISSUE THREAD

**Issue by shun159** [trema/trema#411]
以下のようなコードは

````ruby
send_flow_mod_add(
  datapath_id, 
  match: Match.new({}),
)
````

こう書けたほうがよいかとおもいます。
````ruby
send_flow_mod_add(datapath_id)
````

**Comment by rumb** [comment]
@shun159 さん
デフォルトで全マッチなのですね？！
知りませんでした、ありがとうございます。

**Comment by shun159** [comment]
@rumb いえ、デフォルトでマッチなしのほうが好ましいかと思います。

**Comment by rumb** [comment]
@shun159 さん
経験不足で恐縮なのですが、マッチなしのフローを加える状況があるのでしょうか？
そういう状況があるのであればいいと私は思います。

send_flow_mod_deleteの場合は、逆にデフォルトで全てのフローにマッチして消せるといいかもと思っています。

私のコードですが、下記のコードでswitch_ready後にスイッチに入っているフローを一度初期化しております。
```rb
send_flow_mod_delete(datapath_id, match: Match.new())
```

p.s.
投稿した後に誤解しているのに気が付いたので消したつもりでしたが、消えていなかったでしょうか？
お手数をおかけして申し訳ありません。

**Comment by shun159** [comment]
@rumb 

> マッチなしのフローを加える状況があるのでしょうか？

状況はいろいろあるとおもいます。

例えば,multicastはdropし、broadcastはbroadcastを処理するテーブルへ遷移させ、
その他は、少々に乱暴ですが、unicast として処理するテーブルへ遷移させたい場合など
あるとおもいます。フローの書き方は適当です。table=0から始まってそれぞれのテーブルに遷移するときの一例です。

````
1: priority=3, table=0, eth_dst=multicast_frame_address, actions=drop
2: priority=2, table=0, eth_dst=broadcast_frame_address,note:"this is multicast frame, drop" actions=resubmit(,BROADCAST_TABLE),note:"this is broadcast, resubmit to broadcast handler table"
3: priority=1, table=0, actions=resubmit(,UNICAST_TABLE),note:"assume this is unicast, resubmit to unicast handler"
````
また、単純なACLをFlowTableに落としこむことを考えた場合にも要件次第では、マッチなしのフローの挿入は十分ありうるだろうと思います。

他にご意見があれば、よろしくお願いいたします。

**Comment by rumb** [comment]
@shun159 さん
マッチなしの意味を勘違いしておりました。

非常にいいと思います。
下記のように、AnyMatchやAllMatchといった定数があっても見やすくていいかと思います。
```rb
send_flow_mod_add(
  datapath_id, 
  match: AnyMatch,
)
```

**Comment by rumb** [comment]
現在だと下記コードを実行するとすべてのフローが消えるのですが、先ほどのマッチなしのフローのみを消すことは可能でしょうか？
```rb
send_flow_mod_delete(datapath_id, match: Match.new({}))
```

**Comment by shun159** [comment]
delete_strictは如何でしょう？？

**Comment by shun159** [comment]
@rumb 内容がトピックから逸れそうなので、別のissue で議論した方が良いのかもしれません

**Comment by rumb** [comment]
@shun159 さん
了解しました。
新しいissueを出します。
