### ISSUE TITLE
FileTest.exists? is deprecated

### ISSUE THREAD

**Issue by ebaty** [trema/trema#426]
hello_trema.rbを実行しようとしたところ

```
/trema-0.9.0/lib/trema/command.rb:169:in `create_pid_file': HelloTrema is already running. (RuntimeError)
```

と、このようにalready runningと表示されました。
色々調べた結果、 command.rb L166の`FileTest.exists?` がDeprecatedになっていたので、これを `exist?` に修正すれば無事動作しました。

**Comment by yasuhito** [comment]
Rubyのバージョンはいくつでしょうか?
あと PR を出していただければそのままマージします!

**Comment by ebaty** [comment]
問題が発生した環境でのRubyのversionは2.3でした。
FileTest.exists?自体は2.1からdeprecatedのようです。
なおexist?とexists?は2.0以前において同じ機能のメソッドなので互換性の問題はないと思います。
gemの設定が古いせいかTravis CIが通りませんが、PRを出しました。
